Lab3-4-5
okonstantinova/web pull request #3
Opened 2023-11-16 23:30 UTC by okonstantinova

2023-11-20 07:53 UTC, BakasaRus requested changes

2023-11-20 07:53 UTC, BakasaRus commented on lab-2/js/bento.js
> +    }
Попробуй хранить все элементы в массиве вместо того, чтобы хранить каждый объект отдельно (на это намекает даже нумерация)

2023-11-20 07:53 UTC, BakasaRus commented on lab-2/js/bento.js
> +     const count = localStorage.length;
Здесь нужно будет брать длину массива, а не кол-во элементов в хранилище

2023-11-20 07:53 UTC, BakasaRus commented on lab-2/js/bento.js
> +                '</div>'
Попробуй использовать тег `<template>` для хранения шаблона разметки карточки товара

2023-11-20 07:53 UTC, BakasaRus commented on lab-2/js/bento.js
> +        const item = localStorage.getItem("item-" + i);
Тоже переделать под массив

2023-11-20 07:53 UTC, BakasaRus commented on lab-2/js/bento.js
> +    return 3000;
Это, наверно, можно хранить в самом объекте с тортом

2023-11-21 22:06 UTC, okonstantinova commented on lab-2/js/bento.js
> +    }
теперь хранится в массиве

2023-11-21 22:09 UTC, okonstantinova commented on lab-2/js/bento.js
> +     const count = localStorage.length;
исправила на подсчёт, используя цены, хранящиеся у каждого элемента в массиве

2023-11-21 22:10 UTC, okonstantinova commented on lab-2/js/bento.js
> +                '</div>'
добавила, получилось :)

2023-11-21 22:10 UTC, okonstantinova commented on lab-2/js/bento.js
> +        const item = localStorage.getItem("item-" + i);
тоже переделала

2023-11-21 22:11 UTC, okonstantinova commented on lab-2/js/bento.js
> +    return 3000;
исправила, теперь хранится в объектах массива

2023-11-24 08:28 UTC, BakasaRus approved these changes

2023-11-24 19:42 UTC, merged